#!/usr/bin/env python3
"""Render the bitmap fonts used by the on-device GUI (src/GUI/font_data.c).

Needs Pillow and DejaVu Sans (fonts-dejavu-core). Glyphs are stored 1 bpp,
row-major, MSB first, each glyph starting on a byte boundary.
"""
import sys
import unicodedata
from PIL import Image, ImageDraw, ImageFont

DEJAVU = "/usr/share/fonts/truetype/dejavu/"

ASCII = "".join(chr(c) for c in range(32, 127))


def vietnamese_letters():
    bases = "aăâeêioôơuưy"
    tones = ["", "̀", "́", "̉", "̃", "̣"]
    out = set("đĐ")
    for b in bases + bases.upper():
        for t in tones:
            out.add(unicodedata.normalize("NFC", b + t))
    return "".join(sorted(out))


TEXT_CHARS = ASCII + vietnamese_letters() + "·…°"

FONTS = [
    # name, ttf, pixel size, characters
    ("font_text", "DejaVuSans-Bold.ttf", 15, TEXT_CHARS),
    ("font_small", "DejaVuSans.ttf", 12, TEXT_CHARS),
    ("font_big", "DejaVuSans-Bold.ttf", 28, "0123456789 .,:kmh"),
    ("font_huge", "DejaVuSans-Bold.ttf", 54, "0123456789:"),
]


def render(ttf, size, chars):
    font = ImageFont.truetype(DEJAVU + ttf, size)
    ascent, descent = font.getmetrics()
    glyphs = []
    for ch in sorted(set(chars), key=ord):
        adv = round(font.getlength(ch))
        x0, y0, x1, y1 = font.getbbox(ch, anchor="ls")
        w, h = max(0, x1 - x0), max(0, y1 - y0)
        bits = []
        if w and h:
            img = Image.new("L", (w, h), 0)
            ImageDraw.Draw(img).text((-x0, -y0), ch, font=font, fill=255, anchor="ls")
            px = img.load()
            bits = [1 if px[x, y] >= 110 else 0 for y in range(h) for x in range(w)]
        data = bytearray()
        for i in range(0, len(bits), 8):
            chunk = bits[i:i + 8] + [0] * (8 - len(bits[i:i + 8]))
            data.append(int("".join(map(str, chunk)), 2))
        glyphs.append((ord(ch), w, h, x0, y0, adv, bytes(data)))
    return ascent, descent, glyphs


def main(out_path):
    lines = [
        "// Generated by tools/gen_fonts.py from DejaVu Sans (Bitstream Vera license). Do not edit.",
        '#include "font.h"',
        "",
    ]
    for name, ttf, size, chars in FONTS:
        ascent, descent, glyphs = render(ttf, size, chars)
        bitmap = bytearray()
        table = []
        for cp, w, h, xo, yo, adv, data in glyphs:
            table.append(f"    {{0x{cp:04X}, {w}, {h}, {xo}, {yo}, {adv}, {len(bitmap)}}},")
            bitmap += data
        lines.append(f"static const uint8_t {name}_bitmap[] = {{")
        for i in range(0, len(bitmap), 20):
            lines.append("    " + ", ".join(f"0x{b:02X}" for b in bitmap[i:i + 20]) + ",")
        lines.append("};")
        lines.append(f"static const font_glyph_t {name}_glyphs[] = {{")
        lines += table
        lines.append("};")
        lines.append(
            f"const font_t {name} = {{{name}_glyphs, {len(glyphs)}, {name}_bitmap, {ascent}, {ascent + descent}}};")
        lines.append("")
        print(f"{name}: {len(glyphs)} glyphs, {len(bitmap)} bitmap bytes", file=sys.stderr)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "src/GUI/font_data.c")
